controls:
  boiler:
    name: бойлер
    topic: /devices/wb-mr6cv3_92/controls/K1/on
    states:
      on: "1"
      off: "0"
    labels:
      on: включен
      off: выключен
      unknown: неизвестно

  light:
    name: свет
    topic: /devices/wb-mr6cv3_92/controls/K2/on
    states:
      on: "1"
      off: "0"
    labels:
      on: включен
      off: выключен
      unknown: неизвестно

  climate_temperature:
    name: температура
    topic: /devices/wb-msw-v4_202/controls/Temperature
    unit: "°C"
    precision: 1

  climate_humidity:
    name: влажность
    topic: /devices/wb-msw-v4_202/controls/Humidity
    unit: "%"
    precision: 1

  climate_co2:
    name: CO2
    topic: /devices/wb-msw-v4_202/controls/CO2
    unit: ppm
    precision: 0
